name: Lean CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lean
        uses: leanprover/lean-action@v1
        with:
          auto-config: true

      # ★ ここで強引にマニフェストを生成させる
      - name: Update Lake Manifest
        run: lake update

      - name: Build
        run: lake build
